[package]
authors = ["n_lesnikov"]
name = "aoc2020"
edition = "2018"
version = "0.1.0"

[dependencies]
regex = "1.4.2"
lazy_static = "1.4.0"
smallvec = "1.5.1"
itertools = "0.9.0"
num-bigint = "0.3.0"